"""initial schema

Revision ID: 4aeb62c6ea8e
Revises: 
Create Date: 2026-03-12 13:42:47.940291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeb62c6ea8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_submission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), nullable=False),
    sa.Column('verdict', sa.VARCHAR(length=50), nullable=True),
    sa.Column('time_taken', sa.FLOAT(), nullable=True),
    sa.Column('memory_taken', sa.INTEGER(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
