import math
from flask import Blueprint,request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from ..extentions import db
from ..models import Submission, Problem

submissions_bp = Blueprint("submissions", __name__)

@submissions_bp.route("/submissions", methods=["POST"])
@jwt_required()
def create_submission():
    data=request.get_json()
    allowed_languages=["python", "cpp", "java"]

    if not data:
        return {"error": "Invalid input"}, 400
    
    required_fields=["problem_id", "code", "language"]
    for field in required_fields:
        if field not in data:
            return {"error": f"Missing field: {field}"}, 400
        
    #type checks
    if not isinstance(data["problem_id"], int):
        return {"error": "Problem ID must be an integer"}, 400
    if not isinstance(data["code"], str):
        return {"error": "Code cannot be empty"}, 400
    if not isinstance(data["language"], str):   
        return {"error": "Language must be a string"}, 400
    
    #normalizeing the language input by stripping whitespace and converting to lowercase
    language=data["language"].strip().lower()
    code=data["code"].strip()
    problem_id=data["problem_id"]

    #value checks
    if language not in allowed_languages:
        return {"error": "Unsupported language"}, 400
    if len(code)>1000:
        return {"error": "Code length exceeds limit"}, 400
    if not code:
        return {"error": "Code cannot be empty"}, 400
    
    #db check
    problem=Problem.query.get(problem_id)
    if not problem:
        return {"error":"Problem not found"}, 404
    
    user_id=int(get_jwt_identity())

    submission=Submission(
        user_id=user_id,
        problem_id=problem_id,
        code=code,
        language=language,
        status="IN_QUEUE",
        verdict=None
    )

    db.session.add(submission)
    db.session.commit() #after this the submission.id is automatically generated by the database and can be accessed as submission.id
    return {
        "submission_id": submission.id,
        "status": submission.status,
    },201


#user ek submission dekhna chahta hai khud ka to ek submission id bheji usne
#toh usko wo submission dekhna chahiye
#lekin wo dusre ke submission nahi dekh sakta
#toh isliye humne jwt_required lagaya hai taki user authenticate ho jaye aur get_jwt_identity se user_id mil jaye
#fir hum check karenge ki jo submission hai uska user_id kya hai
#agar wo user_id aur jwt se mila user_id match nahi karta toh hum forbidden error return karenge
#agar match karta hai toh hum submission details return karenge.
@submissions_bp.route("/submissions/<int:submission_id>", methods=["GET"])
@jwt_required()
def get_submission(submission_id):
    user_id=int(get_jwt_identity())
    submission=Submission.query.get(submission_id)
    if not submission:
        return {"error": "Submission not found"}, 404
    if submission.user_id!=user_id:
        return {"error": "Forbidden"}, 403
    return {
        "id": submission.id,
        "problem_id": submission.problem_id,
        "code": submission.code,
        "language": submission.language,
        "status": submission.status,
        "verdict": submission.verdict,
        "time_taken": submission.time_taken,
        "memory_taken": submission.memory_taken,
        "submitted_at": submission.submitted_at.isoformat()
    },200

@submissions_bp.route("/submissions/<int:submission_id>/status", methods=["GET"])
@jwt_required() 
def get_submission_status(submission_id):
    user=int(get_jwt_identity())
    submission=Submission.query.get(submission_id)
    if not submission:
        return {"error": "Submission not found"}, 404
    if submission.user_id!=user:
        return {"error": "Forbidden"}, 403
    return {
        "status": submission.status,
        "verdict": submission.verdict,
        "time_taken": submission.time_taken,
        "memory_taken": submission.memory_taken,
    }

@submissions_bp.route("/submissions", methods=["GET"])
@jwt_required()
def list_submissions():
    user_id=int(get_jwt_identity())

    try:
        page=int(request.args.get("page", 1))
        limit=int(request.args.get("limit", 10))
    except ValueError:
        return {"error": "Page and limit must be integers"}, 400
    
    if(page<1):
        return {"error": "Page must be greater than 0"}, 400
    if(limit<1):  
        return {"error": "Limit must be greater than 0"}, 400
    if(limit>50):
        limit=50

    base_query=Submission.query.filter_by(user_id=user_id)
    total=base_query.count()

    submissions=(
        base_query
        .order_by(Submission.submitted_at.desc())
        .offset((page-1)*limit)
        .limit(limit)
        .all()
    )

    result=[
        {
            "id": s.id,
            "problem_id": s.problem_id,
            "language": s.language,
            "status": s.status,
            "verdict": s.verdict,
            "submitted_at": s.submitted_at.isoformat()
        }
        for s in submissions
    ]
    total_pages=math.ceil(total/limit)
    return{
        "submissions": result,
        "page":page,
        "limit":limit,
        "total":total,
        "total_pages": total_pages
    },200   
